In [106]:
import numpy as np
import matplotlib.pyplot as plt

## 9 observations and 6 variables

In [107]:
np.random.seed(0)

In [141]:
data = np.random.randn(9,6)

In [142]:
data

array([[-1.30652685,  1.65813068, -0.11816405, -0.6801782 ,  0.66638308,
        -0.46071979],
       [-1.33425847, -1.34671751,  0.69377315, -0.15957344, -0.13370156,
         1.07774381],
       [-1.12682581, -0.73067775, -0.38487981,  0.09435159, -0.04217145,
        -0.28688719],
       [-0.0616264 , -0.10730528, -0.71960439, -0.81299299,  0.27451636,
        -0.89091508],
       [-1.15735526, -0.31229225, -0.15766702,  2.2567235 , -0.70470028,
         0.94326072],
       [ 0.74718833, -1.18894496,  0.77325298, -1.18388064, -2.65917224,
         0.60631952],
       [-1.75589058,  0.45093446, -0.6840109 ,  1.6595508 ,  1.0685094 ,
        -0.4533858 ],
       [-0.68783761, -1.2140774 , -0.44092263, -0.2803555 , -0.36469354,
         0.15670386],
       [ 0.5785215 ,  0.34965446, -0.76414392, -1.43779147,  1.36453185,
        -0.68944918]])

In [149]:
mean = np.mean(data,axis=0)

In [150]:
mean

array([-6.78290128e-01, -2.71255061e-01, -2.00262954e-01, -6.04607063e-02,
       -5.89442647e-02,  2.96762156e-04])

In [155]:
zero_mean = np.zeros((9,6))

In [156]:
for i in range(9):
    zero_mean[i,:] = data[i,:] -  mean

In [157]:
zero_mean

array([[-0.62823672,  1.92938574,  0.08209891, -0.6197175 ,  0.72532735,
        -0.46101655],
       [-0.65596834, -1.07546245,  0.89403611, -0.09911273, -0.07475729,
         1.07744704],
       [-0.44853568, -0.45942269, -0.18461686,  0.1548123 ,  0.01677281,
        -0.28718395],
       [ 0.61666373,  0.16394978, -0.51934143, -0.75253228,  0.33346062,
        -0.89121185],
       [-0.47906513, -0.04103719,  0.04259594,  2.3171842 , -0.64575601,
         0.94296396],
       [ 1.42547846, -0.91768989,  0.97351593, -1.12341993, -2.60022797,
         0.60602276],
       [-1.07760046,  0.72218952, -0.48374794,  1.7200115 ,  1.12745366,
        -0.45368257],
       [-0.00954748, -0.94282234, -0.24065968, -0.21989479, -0.30574928,
         0.15640709],
       [ 1.25681163,  0.62090952, -0.56388097, -1.37733077,  1.42347611,
        -0.68974595]])

## c = xx^T/(n-1)

In [164]:
np.dot(zero_mean.T, zero_mean)/(9 - 1)

array([[ 0.80110198, -0.18460298,  0.03834045, -0.79663478, -0.37859036,
        -0.10065795],
       [-0.18460298,  0.96961708, -0.27139272,  0.03082184,  0.7407319 ,
        -0.445078  ],
       [ 0.03834045, -0.27139272,  0.33365979, -0.0968368 , -0.50211581,
         0.33027385],
       [-0.79663478,  0.03082184, -0.0968368 ,  1.56492414,  0.09753111,
         0.30557456],
       [-0.37859036,  0.7407319 , -0.50211581,  0.09753111,  1.40153384,
        -0.55535277],
       [-0.10065795, -0.445078  ,  0.33027385,  0.30557456, -0.55535277,
         0.52658084]])

## np.cov() takes (m,n), m represents # of variables
## if set row_var = 0, then it means m represents # of observations

In [163]:
np.cov(data.T)

array([[ 0.80110198, -0.18460298,  0.03834045, -0.79663478, -0.37859036,
        -0.10065795],
       [-0.18460298,  0.96961708, -0.27139272,  0.03082184,  0.7407319 ,
        -0.445078  ],
       [ 0.03834045, -0.27139272,  0.33365979, -0.0968368 , -0.50211581,
         0.33027385],
       [-0.79663478,  0.03082184, -0.0968368 ,  1.56492414,  0.09753111,
         0.30557456],
       [-0.37859036,  0.7407319 , -0.50211581,  0.09753111,  1.40153384,
        -0.55535277],
       [-0.10065795, -0.445078  ,  0.33027385,  0.30557456, -0.55535277,
         0.52658084]])

## Same!!

## PCA

In [167]:
covariance = np.cov(data.T)

In [168]:
covariance

array([[ 0.80110198, -0.18460298,  0.03834045, -0.79663478, -0.37859036,
        -0.10065795],
       [-0.18460298,  0.96961708, -0.27139272,  0.03082184,  0.7407319 ,
        -0.445078  ],
       [ 0.03834045, -0.27139272,  0.33365979, -0.0968368 , -0.50211581,
         0.33027385],
       [-0.79663478,  0.03082184, -0.0968368 ,  1.56492414,  0.09753111,
         0.30557456],
       [-0.37859036,  0.7407319 , -0.50211581,  0.09753111,  1.40153384,
        -0.55535277],
       [-0.10065795, -0.445078  ,  0.33027385,  0.30557456, -0.55535277,
         0.52658084]])

In [169]:
from numpy import linalg as LA

## The normalized (unit “length”) eigenvectors, such that the column v[:,i] is the eigenvector corresponding to the eigenvalue w[i].

In [170]:
eigenValue, eigenVector = LA.eig(covariance)

In [171]:
eigenValue

array([2.56248593, 2.08105852, 0.01673354, 0.1396961 , 0.36172544,
       0.43571813])

In [172]:
eigenVector

array([[-0.30592151,  0.4287534 , -0.19011475, -0.56366791,  0.60319613,
         0.06979868],
       [ 0.47844192,  0.19238731,  0.13491458, -0.13942573, -0.07801042,
         0.83087505],
       [-0.26858554, -0.09515344, -0.7574641 , -0.19015493, -0.51045315,
         0.21985098],
       [ 0.26625865, -0.78978374, -0.24268048, -0.15737782,  0.46291276,
         0.08601257],
       [ 0.6763357 ,  0.19619372, -0.16764073, -0.43384925, -0.19695834,
        -0.49895577],
       [-0.27756714, -0.32841002,  0.53376526, -0.64318513, -0.34121192,
         0.00923643]])

## covariance . v = lambda . v

In [173]:
np.dot(covariance, eigenVector)

array([[-0.78391956,  0.89226092, -0.00318129, -0.07874221,  0.21819138,
         0.03041255],
       [ 1.22600068,  0.40036924,  0.0022576 , -0.01947723, -0.02821835,
         0.36202732],
       [-0.68824667, -0.19801987, -0.01267506, -0.0265639 , -0.18464389,
         0.09579306],
       [ 0.68228404, -1.64358617, -0.0040609 , -0.02198507,  0.16744732,
         0.03747724],
       [ 1.73310073,  0.40829062, -0.00280522, -0.06060705, -0.07124484,
        -0.21740408],
       [-0.7112619 , -0.68344046,  0.00893178, -0.08985046, -0.12342503,
         0.00402448]])

In [174]:
eigenValue * eigenVector

array([[-0.78391956,  0.89226092, -0.00318129, -0.07874221,  0.21819138,
         0.03041255],
       [ 1.22600068,  0.40036924,  0.0022576 , -0.01947723, -0.02821835,
         0.36202732],
       [-0.68824667, -0.19801987, -0.01267506, -0.0265639 , -0.18464389,
         0.09579306],
       [ 0.68228404, -1.64358617, -0.0040609 , -0.02198507,  0.16744732,
         0.03747724],
       [ 1.73310073,  0.40829062, -0.00280522, -0.06060705, -0.07124484,
        -0.21740408],
       [-0.7112619 , -0.68344046,  0.00893178, -0.08985046, -0.12342503,
         0.00402448]])

In [185]:
zero_mean.shape

(9, 6)

In [186]:
eigenVector.shape

(6, 6)

## Choose three principle components

In [230]:
Vect = eigenVector[:,:2]

In [231]:
Vect

array([[-0.30592151,  0.4287534 ],
       [ 0.47844192,  0.19238731],
       [-0.26858554, -0.09515344],
       [ 0.26625865, -0.78978374],
       [ 0.6763357 ,  0.19619372],
       [-0.27756714, -0.32841002]])

## finaldata = zero_mean * choosen_eigen_vector

In [232]:
FinalData = np.dot(zero_mean, Vect)

In [233]:
FinalData

array([[ 1.54676224,  0.87716863],
       [-0.9300112 , -0.86345828],
       [ 0.09927205, -0.28779479],
       [ 0.30181157,  1.29779919],
       [ 0.03396844, -2.48379548],
       [-3.36257743,  0.52007991],
       [ 2.15154708, -1.26529836],
       [-0.69227875, -0.10026339],
       [ 0.85150601,  2.30556258]])

## Map the data to the vector's direction. Now this FinalData is in a new space and with lower dimension.

## Go back to original data

In [222]:
np.dot(FinalData,  Vect.T) + mean

array([[-0.794453  ,  0.65106572, -0.77512252, -0.36573059,  1.14247079,
        -0.66358037],
       [-0.74765996, -0.89391866,  0.19675003,  0.39470676, -0.8429492 ,
         0.49615647],
       [-0.82624658, -0.28324744, -0.17640877,  0.20067832, -0.0431469 ,
         0.05095588],
       [-0.20454429,  0.11598285, -0.3664044 , -0.99277518,  0.40830276,
        -0.53675358],
       [-1.77310756, -0.71902282, -0.05069764,  1.88536609, -0.5404613 ,
         0.86129155],
       [ 0.59243158, -1.79351573,  0.72929291, -1.34220828, -2.21434017,
         0.70935104],
       [-1.84480216,  0.49044256, -0.52150466,  1.55536717,  1.17813161,
        -0.27736679],
       [-0.55607556, -0.58870414, -0.1903732 , -0.2250588 , -0.5879019 ,
         0.35615623],
       [ 0.04984637,  0.5796221 , -0.64789834, -1.65449184,  0.96939594,
        -0.99353958]])

## Wrap up PCA as a function

In [241]:
def pca(dt, n):
    mean = np.mean(dt,axis=0)
    #calculate zero mean matrix
    data_adjust = dt - mean
    #calculate covariance matrix
    covariance = np.cov(data_adjust, rowvar = 0)
    #calculate eigen values and eigen vectors
    eigenVals, eigenVects = np.linalg.eig(covariance)
    #get the indices of n biggest eigen values
    eigValIndice = np.argsort(eigenVals)[-n:][::-1]
    select_vects = eigenVects[:,eigValIndice]
    final_data = np.dot(data_adjust, select_vects)
    recon_dt = np.dot(final_data, select_vects.T) + mean
    return final_data, recon_dt